name: yordamchi_med
description: "Yordamchi Med - Maxsus ta'limga muhtoj bolalar va ota-onalar uchun monitoring mobil ilovasi."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management & Architecture
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.7

  # Routing
  go_router: ^14.8.1

  # Network & API
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.2

  # UI, Icons, Typography & Charts
  google_fonts: ^6.2.1
  lucide_icons: ^0.257.0
  fl_chart: ^0.70.2
  shimmer: ^3.0.0

  # Maps & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
